#!/bin/bash

# Structured Development: fullstack - Installation Script
# Auto-generated by Claude Workflow Builder

set -e

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 Structured Development: fullstack"
echo "  Multi-Agent Workflow Installer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Check required source directories exist
if [ ! -d "$SCRIPT_DIR/claude" ]; then
  echo "❌ Error: claude/ directory not found in $SCRIPT_DIR"
  echo ""
  echo "Expected ZIP structure:"
  echo "  workflow-config-gen/"
  echo "  ├── install.sh  (this script)"
  echo "  ├── claude/"
  echo "  │   ├── commands/"
  echo "  │   ├── agents/"
  echo "  │   └── CLAUDE.md"
  echo "  └── claude.config/"
  echo ""
  exit 1
fi

# Determine target directory (project root)
if [ -n "$1" ]; then
  TARGET_DIR="$1"
else
  TARGET_DIR="$(pwd)"
fi

echo "📁 Source: $SCRIPT_DIR"
echo "📁 Target: $TARGET_DIR"
echo ""

# Confirm if target is different from script directory
if [ "$TARGET_DIR" = "$SCRIPT_DIR" ]; then
  echo "⚠️  Warning: Installing to the same directory as the ZIP contents."
  echo "   This will rename claude/ to .claude/"
  echo ""
fi

# Check if .claude already exists and explain what will happen
if [ -d "$TARGET_DIR/.claude" ]; then
  echo "📁 Existing .claude/ folder detected."
  echo ""
  echo "   What will happen:"
  echo "   • New files will be added"
  echo "   • Conflicting files will be overwritten"
  echo "   • Other existing files will remain untouched"
  echo ""
  read -p "   Continue? (y/N): " CONTINUE_CONFIRM
  if [ "$CONTINUE_CONFIRM" != "y" ] && [ "$CONTINUE_CONFIRM" != "Y" ]; then
    echo ""
    echo "   Installation cancelled."
    exit 0
  fi
  echo ""
fi

# Install files
echo "📦 Installing workflow files..."
echo ""

# 1. Copy claude/ to .claude/
echo "   [1/3] Copying claude/ → .claude/"
mkdir -p "$TARGET_DIR/.claude"
cp -r "$SCRIPT_DIR/claude/"* "$TARGET_DIR/.claude/" 2>/dev/null || true
echo "         ✓ .claude/commands/study-planner-workflow.md"
echo "         ✓ .claude/agents/study-planner-workflow-*.md"
echo "         ✓ .claude/CLAUDE.md"

# 2. Copy claude.config/ to .claude.config/
if [ -d "$SCRIPT_DIR/claude.config" ]; then
  echo "   [2/3] Copying claude.config/ → .claude.config/"
  mkdir -p "$TARGET_DIR/.claude.config"
  cp -r "$SCRIPT_DIR/claude.config/"* "$TARGET_DIR/.claude.config/" 2>/dev/null || true
  echo "         ✓ .claude.config/study-planner-workflow/"
else
  echo "   [2/3] No claude.config/ found, skipping"
fi

# 3. Copy documentation to project root (optional)
echo "   [3/3] Copying documentation files"
if [ -f "$SCRIPT_DIR/README.md" ]; then
  if [ ! -f "$TARGET_DIR/README.md" ] || [ "$TARGET_DIR" = "$SCRIPT_DIR" ]; then
    cp "$SCRIPT_DIR/README.md" "$TARGET_DIR/WORKFLOW-README.md" 2>/dev/null || true
    echo "         ✓ WORKFLOW-README.md"
  else
    echo "         ⊘ README.md exists, saved as WORKFLOW-README.md"
    cp "$SCRIPT_DIR/README.md" "$TARGET_DIR/WORKFLOW-README.md" 2>/dev/null || true
  fi
fi
if [ -f "$SCRIPT_DIR/QUICKSTART.md" ]; then
  cp "$SCRIPT_DIR/QUICKSTART.md" "$TARGET_DIR/" 2>/dev/null || true
  echo "         ✓ QUICKSTART.md"
fi

# Clean up original folders if installing to same directory
if [ "$TARGET_DIR" = "$SCRIPT_DIR" ]; then
  echo ""
  echo "   [4/4] Cleaning up original folders"
  if [ -d "$SCRIPT_DIR/claude" ]; then
    rm -rf "$SCRIPT_DIR/claude"
    echo "         ✓ Removed claude/ (now .claude/)"
  fi
  if [ -d "$SCRIPT_DIR/claude.config" ]; then
    rm -rf "$SCRIPT_DIR/claude.config"
    echo "         ✓ Removed claude.config/ (now .claude.config/)"
  fi
fi

echo ""
echo "✅ Files installed successfully!"
echo ""

# Optional Configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⚙️  Optional Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. Tool Auto-Approval
echo "1️⃣  Auto-approve workflow tool operations?"
echo "   (Log writes, config file reads)"
read -p "   Enable? (y/N): " APPROVE_CONFIRM

if [ "$APPROVE_CONFIRM" = "y" ] || [ "$APPROVE_CONFIRM" = "Y" ]; then
  SETTINGS_FILE="$TARGET_DIR/.claude/settings.local.json"

  if [ ! -f "$SETTINGS_FILE" ]; then
    echo '{}' > "$SETTINGS_FILE"
  fi

  if command -v node &> /dev/null; then
    node -e "
    const fs = require('fs');
    const settings = JSON.parse(fs.readFileSync('$SETTINGS_FILE', 'utf8'));
    if (!settings.permissions) settings.permissions = {};
    if (!settings.permissions.allow) settings.permissions.allow = [];
    const patterns = [
      'Bash(echo:*)',
      'Read(.claude/**)',
      'Read(.claude.config/**)',
      'Glob(.claude/**)'
    ];
    patterns.forEach(p => { if (!settings.permissions.allow.includes(p)) settings.permissions.allow.push(p); });
    fs.writeFileSync('$SETTINGS_FILE', JSON.stringify(settings, null, 2));
    console.log('   ✓ Auto-approval configured');
    " 2>/dev/null || {
      cat > "$SETTINGS_FILE" << 'ALLOW_EOF'
{
  "permissions": {
    "allow": [
      "Bash(echo:*)",
      "Read(.claude/**)",
      "Read(.claude.config/**)",
      "Glob(.claude/**)"
    ]
  }
}
ALLOW_EOF
      echo "   ✓ Auto-approval configured (basic)"
    }
  else
    cat > "$SETTINGS_FILE" << 'ALLOW_EOF'
{
  "permissions": {
    "allow": [
      "Bash(echo:*)",
      "Read(.claude/**)",
      "Read(.claude.config/**)",
      "Glob(.claude/**)"
    ]
  }
}
ALLOW_EOF
    echo "   ✓ Auto-approval configured"
  fi
else
  echo "   ⊘ Skipped"
fi
echo ""

# Complete
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎉 Installation Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 Installed:"
echo "   .claude/commands/study-planner-workflow.md"
echo "   .claude/agents/study-planner-workflow-*.md"
echo "   .claude/CLAUDE.md"
echo ""
echo "🚀 Usage:"
echo "   /study-planner-workflow <your task>"
echo ""
