# Structured Development: fullstack - Installation Script (Windows PowerShell)
# Auto-generated by Claude Workflow Builder
# Usage: .\install.ps1 [-TargetDir "C:\path\to\project"]

param(
    [string]$TargetDir
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "====================================================" -ForegroundColor Cyan
Write-Host "  Structured Development: fullstack" -ForegroundColor Cyan
Write-Host "  Multi-Agent Workflow Installer (Windows)" -ForegroundColor Cyan
Write-Host "====================================================" -ForegroundColor Cyan
Write-Host ""

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Check source directory
if (-not (Test-Path "$ScriptDir\claude")) {
    Write-Host "[ERROR] claude\ directory not found in $ScriptDir" -ForegroundColor Red
    Write-Host ""
    Write-Host "Expected ZIP structure:"
    Write-Host "  workflow-config-gen\"
    Write-Host "  +-- install.ps1  (this script)"
    Write-Host "  +-- claude\"
    Write-Host "  |   +-- commands\"
    Write-Host "  |   +-- agents\"
    Write-Host "  |   +-- CLAUDE.md"
    Write-Host "  +-- claude.config\"
    exit 1
}

# Target directory (default to current directory if not specified)
if (-not $TargetDir) {
    $TargetDir = (Get-Location).Path
}
# Normalize path (remove trailing slash)
$TargetDir = $TargetDir.TrimEnd('\')
$ScriptDir = $ScriptDir.TrimEnd('\')

Write-Host "[Source] $ScriptDir"
Write-Host "[Target] $TargetDir"
Write-Host ""

# Check if .claude already exists and explain what will happen
if (Test-Path "$TargetDir\.claude") {
    Write-Host "[INFO] Existing .claude\ folder detected."
    Write-Host ""
    Write-Host "   What will happen:"
    Write-Host "   - New files will be added"
    Write-Host "   - Conflicting files will be overwritten"
    Write-Host "   - Other existing files will remain untouched"
    Write-Host ""
    $confirm = Read-Host "   Continue? (y/N)"
    if ($confirm -ne "y" -and $confirm -ne "Y") {
        Write-Host ""
        Write-Host "   Installation cancelled."
        exit 0
    }
    Write-Host ""
}

# Install files
Write-Host "Installing workflow files..."
Write-Host ""

# 1. Copy claude/ to .claude/
Write-Host "   [1/3] Copying claude\ -> .claude\"
New-Item -ItemType Directory -Force -Path "$TargetDir\.claude" | Out-Null
Copy-Item -Path "$ScriptDir\claude\*" -Destination "$TargetDir\.claude\" -Recurse -Force
Write-Host "         [OK] .claude\commands\study-planner-workflow.md"
Write-Host "         [OK] .claude\agents\study-planner-workflow-*.md"
Write-Host "         [OK] .claude\CLAUDE.md"

# 2. Copy claude.config/ to .claude.config/
if (Test-Path "$ScriptDir\claude.config") {
    Write-Host "   [2/3] Copying claude.config\ -> .claude.config\"
    New-Item -ItemType Directory -Force -Path "$TargetDir\.claude.config" | Out-Null
    Copy-Item -Path "$ScriptDir\claude.config\*" -Destination "$TargetDir\.claude.config\" -Recurse -Force
    Write-Host "         [OK] .claude.config\study-planner-workflow\"
} else {
    Write-Host "   [2/3] No claude.config\ found, skipping"
}

# 3. Copy documentation
Write-Host "   [3/3] Copying documentation files"
if (Test-Path "$ScriptDir\README.md") {
    Copy-Item -Path "$ScriptDir\README.md" -Destination "$TargetDir\WORKFLOW-README.md" -Force
    Write-Host "         [OK] WORKFLOW-README.md"
}
if (Test-Path "$ScriptDir\QUICKSTART.md") {
    Copy-Item -Path "$ScriptDir\QUICKSTART.md" -Destination "$TargetDir\" -Force
    Write-Host "         [OK] QUICKSTART.md"
}

# Clean up original folders if installing to same directory
if ($TargetDir -eq $ScriptDir) {
    Write-Host ""
    Write-Host "   [4/4] Cleaning up original folders"
    if (Test-Path "$ScriptDir\claude") {
        Remove-Item -Path "$ScriptDir\claude" -Recurse -Force
        Write-Host "         [OK] Removed claude\ (now .claude\)"
    }
    if (Test-Path "$ScriptDir\claude.config") {
        Remove-Item -Path "$ScriptDir\claude.config" -Recurse -Force
        Write-Host "         [OK] Removed claude.config\ (now .claude.config\)"
    }
}

Write-Host ""
Write-Host "[SUCCESS] Files installed successfully!" -ForegroundColor Green
Write-Host ""

# Optional Configuration
Write-Host "====================================================" -ForegroundColor Cyan
Write-Host "  Optional Configuration" -ForegroundColor Cyan
Write-Host "====================================================" -ForegroundColor Cyan
Write-Host ""

# 1. Tool Auto-Approval
Write-Host "[1] Auto-approve workflow tool operations?"
Write-Host "    (Log writes, config file reads)"
$approveConfirm = Read-Host "    Enable? (y/N)"

if ($approveConfirm -eq "y" -or $approveConfirm -eq "Y") {
    $settingsFile = "$TargetDir\.claude\settings.local.json"

    $settings = @{
        permissions = @{
            allow = @(
                "Bash(echo:*)",
                "Read(.claude/**)",
                "Read(.claude.config/**)",
                "Glob(.claude/**)"
            )
        }
    }

    if (Test-Path $settingsFile) {
        try {
            $existing = Get-Content $settingsFile -Raw | ConvertFrom-Json
            if (-not $existing.permissions) {
                $existing | Add-Member -NotePropertyName "permissions" -NotePropertyValue $settings.permissions -Force
            } elseif (-not $existing.permissions.allow) {
                $existing.permissions | Add-Member -NotePropertyName "allow" -NotePropertyValue $settings.permissions.allow -Force
            }
            $existing | ConvertTo-Json -Depth 10 | Out-File -FilePath $settingsFile -Encoding UTF8
        } catch {
            $settings | ConvertTo-Json -Depth 10 | Out-File -FilePath $settingsFile -Encoding UTF8
        }
    } else {
        $settings | ConvertTo-Json -Depth 10 | Out-File -FilePath $settingsFile -Encoding UTF8
    }
    Write-Host "    [OK] Auto-approval configured"
} else {
    Write-Host "    [SKIP] Skipped"
}
Write-Host ""

# Complete
Write-Host "====================================================" -ForegroundColor Green
Write-Host "  Installation Complete!" -ForegroundColor Green
Write-Host "====================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Installed:"
Write-Host "   .claude\commands\study-planner-workflow.md"
Write-Host "   .claude\agents\study-planner-workflow-*.md"
Write-Host "   .claude\CLAUDE.md"
Write-Host ""
Write-Host "Usage:"
Write-Host "   /study-planner-workflow <your task>"
Write-Host ""
